- roleName: "Admin"
  roleId: 1
  actions: 
  - showVendorMaster
  - showAddVendor
  - addVendor
  - deleteVendor
  - deleteLeave
  - showAttendanceRegister
  - showInwardRegister
  - showInwardEntry
  - showShiftMaster
  - addShift
  - deleteShift
  - showAddShift
  - saveSupervisorSubmitLeave
  - showLeaveRegister
  - checkoutVisitor
  - checkInThisEmployee
  - getClientServiceMappingForThisClient
  - showAddEmployee
  - showSupervisorSubmitLeave
  - saveSupervisorSubmittedLeave
  - showChangePassword
  - showHolidayMaster
  - showAddHoliday
  - addHoliday
  - deleteHoliday
  - showVisitors
  - showAddVisitor
  - addVisitor
  - deleteVisitor
  - showCheckInScreen
  - addRemoveClientServiceMapping
  - getServiceMappingForthisClient
  - showClientServicesMapping
  - notifyjsp
  - showTechnicals
  - showCheckInScreengetOrderDetailsById
  - showUserAudit
  - showHomePage
  - showCategoryMasterNew
  - deleteCategory
  - validateLogin
  - Logout
  - showUserRoleMapping
  - getRoleDetailsForthisUser
  - addRemoveRole
  - showEmployeeMaster
  - addEmployee
  - deleteEmployee
  - showAddEmployee
  - showClientMaster
  - showAddClient
  - addClient
  - deleteClient
  - searchForClient
  - showServiceMaster
  - showAddCategory
  - addService
  - deleteService
  - showAddService
  - showGroupMaster
  - addGroup
  - showAddGroup
  - saveClient
  - showUserDetails
  - showAccessBlockEntry
  - showAddAccessBlockEntry
  - saveAccessBlockEntry
  - deleteAccessBlockEntry
  elements: 
  - 39
  - 40
  - 11
  - 12
  - 21
  - 22
  - 23
  - 24
  - 25
  - 10
  - 700195
  - 700197
  - 700165
  - 700168
  - 700157
  - 700158
  - 700160
  - 700165
  - 32
  - 33
  - 31
  - 34
  - 35
  - 36
  - 37
  - 38
  - 41