- roleName: "Guard"
  roleId: 3
  actions: 
  - checkInGatePass
  - showShortcuts
  - showAccessDenied
  - showScanGatePass
  - showGenerateGatePass
  - addGatePass
  - showGatepassRegister
  - approveGatepass
  - deleteGatepass
  - showGatePassSummary
  - checkoutVisitor
  - showVisitors
  - addVisitor
  - deleteVisitor
  - showAddVisitor
  - showChangePassword
  - showCheckInScreen
  - showHomePage
  - validateLogin
  - Logout
  - checkInThisEmployee
  - showAccessDenied
  - showVendorCheckIn
  - showVendorsCheckIn
  - showCheckInForThisVendor
  - addVendorCheckIn
  - showCheckoutForVendor
  - checkoutVendor 
  - showPrefilledVisitors
  - showScanGatePass
  elements: 
  - 11
  - 21
  - 22
  - 23
  - 24
  - 25
  - 10
  - 700168
  - 700165
  - 700160
  - 700157
  - 700158
  - 43
  - 700165
  - 34
  - 44
  - 700167