- roleName: "Guard"
  roleId: 3
  actions: 
  - checkoutVisitor
  - showVisitors
  - addVisitor
  - deleteVisitor
  - showAddVisitor
  - showChangePassword
  - showCheckInScreen
  - showHomePage
  - validateLogin
  - Logout
  - checkInThisEmployee
  - showAccessDenied
  elements: 
  - 11
  - 21
  - 22
  - 23
  - 24
  - 25
  - 10
  - 700168
  - 700165
  - 700160
  - 700157
  - 700158